### ISSUE TITLE
Dependency Hells (Kitura)

### ISSUE THREAD

**Issue by ugoArangino** [IBM-Swift/Swift-cfenv#10]
When building [Kitura-Starter-Bluemix](https://github.com/IBM-Swift/Kitura-Starter-Bluemix), following error occurs.

```
error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/SwiftyJSON.git)
make: *** [refetch] Error 1
```

**Kitura uses**:
`.Package(url: "https://github.com/IBM-Swift/SwiftyJSON.git", majorVersion: 8)`

and **Swift-cfenv** uses:
`.Package(url: "https://github.com/IBM-Swift/SwiftyJSON.git", majorVersion: 7)`

```
Cloning https://github.com/IBM-Swift/Kitura.git
Resolved version: 0.17.5
Cloning https://github.com/IBM-Swift/SwiftyJSON.git
Resolved version: 8.1.1
Cloning https://github.com/IBM-Swift/Swift-cfenv
Resolved version: 1.2.1
error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/SwiftyJSON.git)
make: *** [refetch] Error 1
```

https://github.com/apple/swift-package-manager/blob/master/Documentation/DependencyHells.md

**Comment by rolivieri** [comment]
@ugoArangino - I cannot reproduce the problem you are seeing. Can you double check you have the latest code for the [Kitura-Starter-Bluemix](https://github.com/IBM-Swift/Kitura-Starter-Bluemix) app?I just built it again now just fine. I would suggest you pull down the latest code from master, do a `make clean`, followed by a `make refetch`, followed by a `make`. Here's the output I get after doing so:

```
$ make clean
--- Invoking swift build --clean
swift build --clean
Ricardos-MacBook-Pro:Kitura-Starter-Bluemix olivieri$ make refetch
--- Removing Packages directory
rm -rf Packages
--- Fetching dependencies
swift build --fetch
Cloning https://github.com/IBM-Swift/Kitura.git
Resolved version: 0.16.1
Cloning https://github.com/IBM-Swift/Kitura-net.git
Resolved version: 0.16.0
Cloning https://github.com/IBM-Swift/Kitura-sys.git
Resolved version: 0.16.0
Cloning https://github.com/IBM-Swift/LoggerAPI.git
Resolved version: 0.8.0
Cloning https://github.com/IBM-Swift/BlueSocket.git
Resolved version: 0.5.20
Cloning https://github.com/IBM-Swift/CCurl.git
Resolved version: 0.1.1
Cloning https://github.com/IBM-Swift/CHttpParser.git
Resolved version: 0.1.1
Cloning https://github.com/IBM-Swift/SwiftyJSON.git
Resolved version: 7.0.4
Cloning https://github.com/IBM-Swift/Kitura-TemplateEngine.git
Resolved version: 0.16.0
Cloning https://github.com/IBM-Swift/HeliumLogger.git
Resolved version: 0.8.0
Cloning https://github.com/IBM-Swift/Swift-cfenv
Resolved version: 1.2.1
Ricardos-MacBook-Pro:Kitura-Starter-Bluemix olivieri$ make
--- Running build on Darwin
--- Build scripts directory: Kitura-Build/build
--- Checking swift version
swift --version
Apple Swift version 3.0-dev (LLVM dffa09ffd8, Clang 1e6cba3ce3, Swift d2aee43220)
Target: x86_64-apple-macosx10.9
--- Checking swiftc version
swiftc --version
Apple Swift version 3.0-dev (LLVM dffa09ffd8, Clang 1e6cba3ce3, Swift d2aee43220)
Target: x86_64-apple-macosx10.9
--- Checking git revision and branch
git rev-parse HEAD
e666f8df6d4af3f1fff73b3e12acdf9ce7f985db
git rev-parse --abbrev-ref HEAD
master
--- Invoking swift build
swift build  
note: you may be able to install libcurl using your system-packager:

    brew install curl

note: you may be able to install libcurl using your system-packager:

    brew install curl

note: you may be able to install libcurl using your system-packager:

    brew install curl

note: you may be able to install libcurl using your system-packager:

    brew install curl

mkdir -p /Users/olivieri/git/Kitura-Starter-Bluemix/.build/debug/CHttpParser.build
Compile CHttpParser utils.c
Compile CHttpParser http_parser.c
Compile Swift Module 'LoggerAPI' (1 sources)
Compile Swift Module 'Socket' (3 sources)
Compile Swift Module 'SwiftyJSON' (3 sources)
Compile Swift Module 'KituraTemplateEngine' (1 sources)
Compile Swift Module 'KituraSys' (4 sources)
Compile Swift Module 'HeliumLogger' (1 sources)
Linking CHttpParser
Compile Swift Module 'KituraNet' (13 sources)
Compile Swift Module 'CloudFoundryEnv' (7 sources)
Compile Swift Module 'Kitura' (23 sources)
Compile Swift Module 'KituraStarterBluemix' (1 sources)
Linking .build/debug/Kitura-Starter-Bluemix
```

**Comment by ugoArangino** [comment]
I tryed do is like you described it, but I am getting following errors after `Linking CHttpParser`

	$ git clone https://github.com/IBM-Swift/Kitura-Starter-Bluemix.git
	Cloning into 'Kitura-Starter-Bluemix'...
	remote: Counting objects: 80, done.
	remote: Total 80 (delta 0), reused 0 (delta 0), pack-reused 80
	Unpacking objects: 100% (80/80), done.
	Checking connectivity... done.

---

	$ cd Kitura-Starter-Bluemix

---

	$ make clean refetch 
	--- Fetching Kitura-Build submodule
	git submodule init
	Submodule 'Kitura-Build' (https://github.com/IBM-Swift/Kitura-Build.git) registered for path 'Kitura-Build'
	git submodule update --remote --merge
	Cloning into 'Kitura-Build'...
	remote: Counting objects: 450, done.
	remote: Compressing objects: 100% (26/26), done.
	remote: Total 450 (delta 11), reused 0 (delta 0), pack-reused 424
	Receiving objects: 100% (450/450), 64.92 KiB | 0 bytes/s, done.
	Resolving deltas: 100% (229/229), done.
	Checking connectivity... done.
	Submodule path 'Kitura-Build': checked out 'f7b5be7f7f89215eadeda03ef8c4b42356f9221a'
	--- Invoking swift build --clean
	swift build --clean
	rm -rf .build
	--- Removing Packages directory
	rm -rf Packages
	--- Fetching dependencies
	swift build --fetch
	Cloning https://github.com/IBM-Swift/Kitura.git
	Resolved version: 0.16.1
	Cloning https://github.com/IBM-Swift/Kitura-net.git
	Resolved version: 0.16.0
	Cloning https://github.com/IBM-Swift/Kitura-sys.git
	Resolved version: 0.16.0
	Cloning https://github.com/IBM-Swift/LoggerAPI.git
	Resolved version: 0.8.0
	Cloning https://github.com/IBM-Swift/BlueSocket.git
	Resolved version: 0.5.20
	Cloning https://github.com/IBM-Swift/CCurl.git
	Resolved version: 0.1.1
	Cloning https://github.com/IBM-Swift/CHttpParser.git
	Resolved version: 0.1.1
	Cloning https://github.com/IBM-Swift/SwiftyJSON.git
	Resolved version: 7.0.4
	Cloning https://github.com/IBM-Swift/Kitura-TemplateEngine.git
	Resolved version: 0.16.0
	Cloning https://github.com/IBM-Swift/HeliumLogger.git
	Resolved version: 0.8.0
	Cloning https://github.com/IBM-Swift/Swift-cfenv
	Resolved version: 1.2.1

---

	$ make
	--- Running build on Darwin
	--- Build scripts directory: Kitura-Build/build
	--- Checking swift version
	swift --version
	Apple Swift version 3.0-dev (LLVM dffa09ffd8, Clang 9f0d189820, Swift 1c720b8f84)
	Target: x86_64-apple-macosx10.9
	--- Checking swiftc version
	swiftc --version
	Apple Swift version 3.0-dev (LLVM dffa09ffd8, Clang 9f0d189820, Swift 1c720b8f84)
	Target: x86_64-apple-macosx10.9
	--- Checking git revision and branch
	git rev-parse HEAD
	e666f8df6d4af3f1fff73b3e12acdf9ce7f985db
	git rev-parse --abbrev-ref HEAD
	master
	--- Invoking swift build
	swift build  
	note: you may be able to install libcurl using your system-packager:

	   brew install curl

	note: you may be able to install libcurl using your system-packager:

	   brew install curl

	note: you may be able to install libcurl using your system-packager:

	   brew install curl

	note: you may be able to install libcurl using your system-packager:

	   brew install curl

	Compile CHttpParser utils.c
	Compile CHttpParser http_parser.c
	Compile Swift Module 'LoggerAPI' (1 sources)
	Compile Swift Module 'Socket' (3 sources)
	Compile Swift Module 'SwiftyJSON' (3 sources)
	Compile Swift Module 'KituraTemplateEngine' (1 sources)
	Compile Swift Module 'KituraSys' (4 sources)
	Compile Swift Module 'HeliumLogger' (1 sources)
	Linking CHttpParser
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:124:14: error: cannot invoke 'JSON.init' with an argument list of type '([AnyObject])'
		   self.init(jsonArray.map { $0.object })
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:124:14: note: overloads for 'JSON.init' exist with these partially matching parameter lists: (AnyObject), ([JSON]), ([String : JSON])
		   self.init(jsonArray.map { $0.object })
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:143:14: error: cannot invoke 'JSON.init' with an argument list of type '([String : AnyObject])'
		   self.init(dictionary)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:143:14: note: overloads for 'JSON.init' exist with these partially matching parameter lists: (AnyObject), ([JSON]), ([String : JSON])
		   self.init(dictionary)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:296:29: error: return expression of type '[AnyObject]' does not conform to 'AnyObject'
				   return self.rawArray
						  ~~~~~^~~~~~~~
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:298:29: error: return expression of type '[String : AnyObject]' does not conform to 'AnyObject'
				   return self.rawDictionary
						  ~~~~~^~~~~~~~~~~~~
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:300:29: error: return expression of type 'String' does not conform to 'AnyObject'
				   return self.rawString
						  ~~~~~^~~~~~~~~
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:332:94: error: cannot convert value of type 'String' to expected dictionary key type 'NSObject'
				   _error = NSError(domain: ErrorDomain, code: ErrorUnsupportedType, userInfo: [NSLocalizedDescriptionKey: "It is a unsupported type"])
																								^~~~~~~~~~~~~~~~~~~~~~~~~
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:638:105: error: cannot convert value of type 'String' to expected dictionary key type 'NSObject'
				   r._error = self._error ?? NSError(domain: ErrorDomain, code: ErrorWrongType, userInfo: [NSLocalizedDescriptionKey: "Array[\(index)] failure, It is not an array"])
																										   ^~~~~~~~~~~~~~~~~~~~~~~~~
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:644:97: error: cannot convert value of type 'String' to expected dictionary key type 'NSObject'
				   r._error = NSError(domain: ErrorDomain, code:ErrorIndexOutOfBounds , userInfo: [NSLocalizedDescriptionKey: "Array[\(index)] is out of bounds"])
																								   ^~~~~~~~~~~~~~~~~~~~~~~~~
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:665:93: error: cannot convert value of type 'String' to expected dictionary key type 'NSObject'
					   r._error = NSError(domain: ErrorDomain, code: ErrorNotExist, userInfo: [NSLocalizedDescriptionKey: "Dictionary[\"\(key)\"] does not exist"])
																							   ^~~~~~~~~~~~~~~~~~~~~~~~~
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:668:105: error: cannot convert value of type 'String' to expected dictionary key type 'NSObject'
				   r._error = self._error ?? NSError(domain: ErrorDomain, code: ErrorWrongType, userInfo: [NSLocalizedDescriptionKey: "Dictionary[\"\(key)\"] failure, It is not an dictionary"])
																										   ^~~~~~~~~~~~~~~~~~~~~~~~~
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:753:14: error: cannot invoke 'JSON.init' with an argument list of type '(StringLiteralType)'
		   self.init(value)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:753:14: note: overloads for 'JSON.init' exist with these partially matching parameter lists: (AnyObject), ([JSON]), ([String : JSON])
		   self.init(value)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:757:14: error: cannot invoke 'JSON.init' with an argument list of type '(StringLiteralType)'
		   self.init(value)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:757:14: note: overloads for 'JSON.init' exist with these partially matching parameter lists: (AnyObject), ([JSON]), ([String : JSON])
		   self.init(value)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:761:14: error: cannot invoke 'JSON.init' with an argument list of type '(StringLiteralType)'
		   self.init(value)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:761:14: note: overloads for 'JSON.init' exist with these partially matching parameter lists: (AnyObject), ([JSON]), ([String : JSON])
		   self.init(value)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:768:14: error: cannot invoke 'JSON.init' with an argument list of type '(IntegerLiteralType)'
		   self.init(value)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:768:14: note: overloads for 'JSON.init' exist with these partially matching parameter lists: (AnyObject), ([JSON]), ([String : JSON])
		   self.init(value)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:775:14: error: cannot invoke 'JSON.init' with an argument list of type '(BooleanLiteralType)'
		   self.init(value)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:775:14: note: overloads for 'JSON.init' exist with these partially matching parameter lists: (AnyObject), ([JSON]), ([String : JSON])
		   self.init(value)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:782:14: error: cannot invoke 'JSON.init' with an argument list of type '(FloatLiteralType)'
		   self.init(value)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:782:14: note: overloads for 'JSON.init' exist with these partially matching parameter lists: (AnyObject), ([JSON]), ([String : JSON])
		   self.init(value)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:789:14: error: cannot invoke 'JSON.init' with an argument list of type '([String : AnyObject])'
		   self.init(elements.reduce([String : AnyObject](minimumCapacity: elements.count)){(dictionary: [String : AnyObject], element:(String, AnyObject)) -> [String : AnyObject] in
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:789:14: note: overloads for 'JSON.init' exist with these partially matching parameter lists: (AnyObject), ([JSON]), ([String : JSON])
		   self.init(elements.reduce([String : AnyObject](minimumCapacity: elements.count)){(dictionary: [String : AnyObject], element:(String, AnyObject)) -> [String : AnyObject] in
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:800:14: error: cannot invoke 'JSON.init' with an argument list of type '([AnyObject])'
		   self.init(elements)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:800:14: note: overloads for 'JSON.init' exist with these partially matching parameter lists: (AnyObject), ([JSON]), ([String : JSON])
		   self.init(elements)
				^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:848:83: error: cannot convert value of type 'String' to expected dictionary key type 'NSObject'
			   throw NSError(domain: ErrorDomain, code: ErrorInvalidJSON, userInfo: [NSLocalizedDescriptionKey: "JSON is invalid"])
																					 ^~~~~~~~~~~~~~~~~~~~~~~~~
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:978:31: error: value of type '[AnyObject]' does not conform to 'AnyObject' in assignment
				   self.object = array
								 ^~~~~
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:1050:31: error: value of type '[String : AnyObject]' does not conform to 'AnyObject' in assignment
				   self.object = v
								 ^
	xyz/Kitura-Starter-Bluemix/Packages/SwiftyJSON-7.0.4/Source/SwiftyJSON.swift:1274:37: error: cannot convert value of type 'String?' to expected argument type 'AnyObject?'
			   self.object = newValue?.absoluteString ?? NSNull()
							 ~~~~~~~~~~^~~~~~~~~~~~~~
	<unknown>:0: error: build had 1 command failures
	error: exit(1): /Library/Developer/Toolchains/swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a.xctoolchain/usr/bin/swift-build-tool -f xyz/Kitura-Starter-Bluemix/.build/debug.yaml
	make: *** [build] Error 1

**Comment by shmuelk** [comment]
@ugoArangino Exactly what version of Swift 3.0 are you using? The application you are trying to build works with the 05/03 driver of Swift 3.0.

**Comment by ugoArangino** [comment]
I am using `swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a ` as described in the Kitura documentation. 
https://github.com/IBM-Swift/Kitura#swift-version

**Comment by rolivieri** [comment]
@ugoArangino - As Samuel mentioned above, the [Kitura-Starter-Bluemix](https://github.com/IBM-Swift/Kitura-Starter-Bluemix) app is compatible with the `DEVELOPMENT-SNAPSHOT-2016-05-03-a` binaries (not with the `swift-DEVELOPMENT-SNAPSHOT-2016-05-09-a` binaries). We have this documented on the [README](https://github.com/IBM-Swift/Kitura-Starter-Bluemix) here under the `Swift Version` section (second section in the README).

**Comment by ugoArangino** [comment]
I works now. Thank you very much.
I was to focused on the Kitura [documentation](https://github.com/IBM-Swift/Kitura#swift-version).
