### ISSUE TITLE
Swift-cfenv 4.x is not compatible with Swift 3.0.2

### ISSUE THREAD

**Issue by tunniclm** [IBM-Swift/Swift-cfenv#59]
It would be nice if Swift-cfenv maintained some level of back-compatibility with Swift. For example, Kitura 1.7 works with Swift 3.0.2 and Swift 3.1.1.

Currently I am seeing the following error when compiling my project on Swift 3.0.2 when using Kitura 1.7, CloudConfiguration 2.x, Swift-cfenv 4.x:

```
/tmp/041ffec28bc23291ae0b059c3a2123aa393d3991/swiftserver/Packages/CloudFoundryEnv-4.0.2/Sources/CloudFoundryEnv/AppEnv.swift:184:23: error: use of unresolved identifier 'NSRegularExpression'
      let regex = try NSRegularExpression(pattern: spec, options: NSRegularExpression.Options.caseInsensitive)
                      ^~~~~~~~~~~~~~~~~~~
Foundation.RegularExpression:1:12: note: did you mean 'RegularExpression'?
open class RegularExpression : Foundation.NSObject, NSCopying, NSCoding {
           ^
/tmp/041ffec28bc23291ae0b059c3a2123aa393d3991/swiftserver/Packages/CloudFoundryEnv-4.0.2/Sources/CloudFoundryEnv/AppEnv.swift:184:67: error: use of unresolved identifier 'NSRegularExpression'
      let regex = try NSRegularExpression(pattern: spec, options: NSRegularExpression.Options.caseInsensitive)
                                                                  ^~~~~~~~~~~~~~~~~~~
Foundation.RegularExpression:1:12: note: did you mean 'RegularExpression'?
open class RegularExpression : Foundation.NSObject, NSCopying, NSCoding {
           ^
<unknown>:0: error: build had 1 command failures
```

**Comment by rolivieri** [comment]
@tunniclm Let's discuss this during the planning meeting on Monday. We on purpose skipped supporting Swift 3.0.2 in the latest release.

**Comment by ianpartridge** [comment]
This ship has sailed :)
